NewhopeCity_House2_MapScripts::
	.byte 0

NewhopeCity_House2_EventScript_PokefanF::
	msgbox NewhopeCity_House2_Text_TrainerSchoolExcellent, MSGBOX_NPC
	end

NewhopeCity_House2_EventScript_LittleGirl::
	msgbox NewhopeCity_House2_Text_RoxanneKnowsALot, MSGBOX_NPC
	end

NewhopeCity_House2_Text_TrainerSchoolExcellent:
	.string "The TRAINER'S SCHOOL is excellent.\p"
	.string "If you study there, you could even\n"
	.string "become a GYM LEADER.$"

NewhopeCity_House2_Text_RoxanneKnowsALot:
	.string "ROXANNE, the GYM LEADER, really knows\n"
	.string "a lot about POKéMON.\p"
	.string "She's really strong, too!$"

