.set LOCALID_LITTLE_BOY, 7
.set LOCALID_LITTLE_GIRL, 8
.set LOCALID_DEVON_EMPLOYEE, 9
.set LOCALID_GRUNT, 10
.set LOCALID_RIVAL, 14
.set LOCALID_SCIENTIST, 15

NewhopeCity_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, NewhopeCity_OnTransition
	map_script MAP_SCRIPT_ON_FRAME_TABLE, NewhopeCity_OnFrame
	.byte 0

NewhopeCity_OnTransition:
	setflag FLAG_VISITED_NEWHOPE_CITY
	call Common_EventScript_SetupRivalGfxId
	call_if_eq VAR_NEWHOPE_CITY_STATE, 6, NewhopeCity_EventScript_HideMapNamePopup
	getplayerxy VAR_TEMP_0, VAR_TEMP_1
	goto_if_eq VAR_NEWHOPE_CITY_STATE, 6, NewhopeCity_EventScript_PositionScientistForExit
	end

NewhopeCity_EventScript_PositionScientistForExit::
	goto_if_eq VAR_TEMP_0, 11, NewhopeCity_EventScript_PositionScientistLeftExit
	setobjectxyperm LOCALID_SCIENTIST, 12, 15
	end

NewhopeCity_EventScript_PositionScientistLeftExit::
	setobjectxyperm LOCALID_SCIENTIST, 11, 15
	end

NewhopeCity_EventScript_HideMapNamePopup::
	setflag FLAG_HIDE_MAP_NAME_POPUP
	return

NewhopeCity_OnFrame:
	map_script_2 VAR_NEWHOPE_CITY_STATE, 6, NewhopeCity_EventScript_ScientistAddMatchCall
	.2byte 0

NewhopeCity_EventScript_ScientistAddMatchCall::
	lockall
	setvar VAR_ROUTE104_STATE, 1
	applymovement OBJ_EVENT_ID_PLAYER, NewhopeCity_Movement_PlayerWalkDown
	waitmovement 0
	playse SE_EXIT
	delay 10
	addobject LOCALID_SCIENTIST
	applymovement LOCALID_SCIENTIST, NewhopeCity_Movement_ScientistApproachPlayer
	waitmovement 0
	playse SE_PIN
	applymovement LOCALID_SCIENTIST, Common_Movement_ExclamationMark
	waitmovement 0
	applymovement LOCALID_SCIENTIST, Common_Movement_Delay48
	waitmovement 0
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkInPlaceFasterUp
	waitmovement 0
	applymovement LOCALID_SCIENTIST, NewhopeCity_Movement_ScientistWalkInPlaceDown
	waitmovement 0
	msgbox NewhopeCity_Text_DevelopedNewPokenavFeature, MSGBOX_DEFAULT
	closemessage
	setflag FLAG_HAS_MATCH_CALL
	applymovement LOCALID_SCIENTIST, Common_Movement_WalkInPlaceFasterLeft
	waitmovement 0
	playse SE_CLICK
	delay 10
	playse SE_CLICK
	delay 10
	playse SE_CLICK
	delay 10
	playse SE_CLICK
	delay 20
	applymovement LOCALID_SCIENTIST, Common_Movement_WalkInPlaceFasterDown
	waitmovement 0
	msgbox NewhopeCity_Text_AddedMatchCallPleaseCallMrStone, MSGBOX_DEFAULT
	closemessage
	delay 20
	goto NewhopeCity_EventScript_MatchCallTutorial

NewhopeCity_EventScript_PleaseSelectPokenav::
	msgbox NewhopeCity_Text_PleaseSelectPokenav, MSGBOX_DEFAULT
	closemessage
	delay 10
	goto NewhopeCity_EventScript_MatchCallTutorial

NewhopeCity_EventScript_MatchCallTutorial::
	setflag FLAG_ADDED_MATCH_CALL_TO_POKENAV
	special ScriptMenu_CreateStartMenuForPokenavTutorial
	waitstate
	switch VAR_RESULT
	case 0, NewhopeCity_EventScript_PleaseSelectPokenav
	case 1, NewhopeCity_EventScript_PleaseSelectPokenav
	case 2, NewhopeCity_EventScript_PleaseSelectPokenav
	case 4, NewhopeCity_EventScript_PleaseSelectPokenav
	case 5, NewhopeCity_EventScript_PleaseSelectPokenav
	case 6, NewhopeCity_EventScript_PleaseSelectPokenav
	case 7, NewhopeCity_EventScript_PleaseSelectPokenav
	case MULTI_B_PRESSED, NewhopeCity_EventScript_PleaseSelectPokenav
	special OpenPokenavForTutorial
	waitstate
	delay 20
	msgbox NewhopeCity_Text_IdBetterGetBackToWork, MSGBOX_DEFAULT
	closemessage
	applymovement LOCALID_SCIENTIST, NewhopeCity_Movement_ScientistLeave
	waitmovement 0
	playse SE_EXIT
	removeobject LOCALID_SCIENTIST
	setflag FLAG_HIDE_NEWHOPE_CITY_SCIENTIST
	setvar VAR_NEWHOPE_CITY_STATE, 7
	clearflag FLAG_HIDE_MAP_NAME_POPUP
	releaseall
	end

NewhopeCity_Movement_ScientistWalkInPlaceDown:
	walk_in_place_down
	step_end

NewhopeCity_Movement_PlayerWalkDown:
	walk_down
	step_end

NewhopeCity_Movement_ScientistApproachPlayer:
	walk_down
	delay_16
	step_end

@ Unused
NewhopeCity_Movement_ScientistWalkAroundPlayer:
	delay_16
	walk_left
	walk_down
	walk_down
	walk_right
	walk_in_place_faster_up
	delay_16
	step_end

NewhopeCity_Movement_ScientistLeave:
	walk_up
	step_end

NewhopeCity_EventScript_FatMan::
	lock
	faceplayer
	goto_if_set FLAG_DEVON_GOODS_STOLEN, NewhopeCity_EventScript_FatManSawGrunt
	msgbox NewhopeCity_Text_WeShortenItToDevon, MSGBOX_DEFAULT
	release
	end

NewhopeCity_EventScript_FatManSawGrunt::
	msgbox NewhopeCity_Text_SneakyLookingManWentAroundCorner, MSGBOX_DEFAULT
	release
	end

NewhopeCity_EventScript_DevonEmployee2::
	lock
	faceplayer
	msgbox NewhopeCity_Text_YoureNewAroundHere, MSGBOX_DEFAULT
	release
	end

NewhopeCity_EventScript_Woman::
	msgbox NewhopeCity_Text_GymLeaderIsntEasyWithFire, MSGBOX_NPC
	end

NewhopeCity_EventScript_Man1::
	lock
	faceplayer
	goto_if_set FLAG_BADGE01_GET, NewhopeCity_EventScript_Man1HaveBadge
	msgbox NewhopeCity_Text_HaveYouChallengedGym, MSGBOX_DEFAULT
	release
	end

NewhopeCity_EventScript_Man1HaveBadge::
	msgbox NewhopeCity_Text_HeyThatsNewhopesGymBadge, MSGBOX_DEFAULT
	release
	end

NewhopeCity_EventScript_Boy2::
	lock
	faceplayer
	goto_if_set FLAG_RECEIVED_POKENAV, NewhopeCity_EventScript_Boy2BrineyLeftTunnel
	msgbox NewhopeCity_Text_MrBrineyWalksInTheTunnel, MSGBOX_DEFAULT
	release
	end

NewhopeCity_EventScript_Boy2BrineyLeftTunnel::
	msgbox NewhopeCity_Text_MrBrineyLovesPeeko, MSGBOX_DEFAULT
	release
	end

NewhopeCity_EventScript_Twin::
	msgbox NewhopeCity_Text_WowYouHavePokemon, MSGBOX_NPC
	end

NewhopeCity_EventScript_NinjaBoy::
	msgbox NewhopeCity_Text_CatchRarePokemonIfIGoToSchool, MSGBOX_SIGN
	end

NewhopeCity_EventScript_TunnelSign::
	msgbox NewhopeCity_Text_TunnelNearingCompletion, MSGBOX_SIGN
	end

NewhopeCity_EventScript_DevonCorpSign::
	msgbox NewhopeCity_Text_DevonCorpSign, MSGBOX_SIGN
	end

NewhopeCity_EventScript_GymSign::
	msgbox NewhopeCity_Text_GymSign, MSGBOX_SIGN
	end

@ Unused
NewhopeCity_EventScript_DevonCorpBranchOfficeSign::
	msgbox NewhopeCity_Text_DevonCorpBranchOfficeSign, MSGBOX_SIGN
	end

NewhopeCity_EventScript_CitySign::
	msgbox NewhopeCity_Text_CitySign, MSGBOX_SIGN
	end

NewhopeCity_EventScript_TrainersSchoolSign::
	msgbox NewhopeCity_Text_TrainersSchoolSign, MSGBOX_SIGN
	end

NewhopeCity_EventScript_CuttersHouseSign::
	msgbox NewhopeCity_Text_CuttersHouse, MSGBOX_SIGN
	end

NewhopeCity_EventScript_LittleBoy::
	lock
	faceplayer
	msgbox NewhopeCity_Text_PokemonCanChangeLookFromExp, MSGBOX_DEFAULT
	applymovement LOCALID_LITTLE_BOY, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

NewhopeCity_EventScript_LittleGirl::
	lock
	faceplayer
	msgbox NewhopeCity_Text_PokemonChangeShape, MSGBOX_DEFAULT
	applymovement LOCALID_LITTLE_GIRL, Common_Movement_FaceOriginalDirection
	waitmovement 0
	release
	end

NewhopeCity_EventScript_Man2::
	lock
	faceplayer
	msgbox NewhopeCity_Text_TradePokemonGrowFast, MSGBOX_DEFAULT
	release
	end

NewhopeCity_EventScript_StolenGoodsTrigger0::
	lockall
	setobjectxyperm LOCALID_DEVON_EMPLOYEE, 14, 21
	setobjectmovementtype LOCALID_DEVON_EMPLOYEE, MOVEMENT_TYPE_FACE_RIGHT
	setvar VAR_0x8004, 0
	goto NewhopeCity_EventScript_StolenGoodsScene
	end

NewhopeCity_EventScript_StolenGoodsTrigger1::
	lockall
	setobjectxyperm LOCALID_DEVON_EMPLOYEE, 14, 21
	setobjectmovementtype LOCALID_DEVON_EMPLOYEE, MOVEMENT_TYPE_FACE_RIGHT
	setvar VAR_0x8004, 1
	goto NewhopeCity_EventScript_StolenGoodsScene
	end

NewhopeCity_EventScript_StolenGoodsTrigger2::
	lockall
	setobjectxyperm LOCALID_DEVON_EMPLOYEE, 14, 21
	setobjectmovementtype LOCALID_DEVON_EMPLOYEE, MOVEMENT_TYPE_FACE_RIGHT
	setvar VAR_0x8004, 2
	goto NewhopeCity_EventScript_StolenGoodsScene
	end

NewhopeCity_EventScript_StolenGoodsTrigger3::
	lockall
	setobjectxyperm LOCALID_DEVON_EMPLOYEE, 14, 21
	setobjectmovementtype LOCALID_DEVON_EMPLOYEE, MOVEMENT_TYPE_FACE_RIGHT
	setvar VAR_0x8004, 3
	goto NewhopeCity_EventScript_StolenGoodsScene
	end

NewhopeCity_EventScript_StolenGoodsTrigger4::
	lockall
	setobjectxyperm LOCALID_DEVON_EMPLOYEE, 14, 21
	setobjectmovementtype LOCALID_DEVON_EMPLOYEE, MOVEMENT_TYPE_FACE_RIGHT
	setvar VAR_0x8004, 4
	goto NewhopeCity_EventScript_StolenGoodsScene
	end

NewhopeCity_EventScript_StolenGoodsScene::
	msgbox NewhopeCity_Text_OutOfTheWay, MSGBOX_DEFAULT
	closemessage
	playbgm MUS_ENCOUNTER_AQUA, FALSE
	addobject LOCALID_GRUNT
	addobject LOCALID_DEVON_EMPLOYEE
	applymovement LOCALID_GRUNT, NewhopeCity_Movement_GruntEscape
	waitmovement 0
	removeobject LOCALID_GRUNT
	applymovement LOCALID_DEVON_EMPLOYEE, NewhopeCity_Movement_EmployeeChaseGrunt1
	waitmovement 0
	msgbox NewhopeCity_Text_WaitDontTakeMyGoods, MSGBOX_DEFAULT
	closemessage
	applymovement LOCALID_DEVON_EMPLOYEE, NewhopeCity_Movement_EmployeeChaseGrunt2
	waitmovement 0
	fadedefaultbgm
	removeobject LOCALID_DEVON_EMPLOYEE
	setobjectxyperm LOCALID_DEVON_EMPLOYEE, 30, 10
	clearflag FLAG_HIDE_NEWHOPE_CITY_DEVON_EMPLOYEE_1
	setflag FLAG_DEVON_GOODS_STOLEN
	setvar VAR_NEWHOPE_CITY_STATE, 2
	setvar VAR_RUSTURF_TUNNEL_STATE, 2
	setvar VAR_ROUTE116_STATE, 1
	clearflag FLAG_HIDE_ROUTE_116_MR_BRINEY
	clearflag FLAG_HIDE_RUSTURF_TUNNEL_PEEKO
	clearflag FLAG_HIDE_RUSTURF_TUNNEL_AQUA_GRUNT
	setflag FLAG_HIDE_BRINEYS_HOUSE_MR_BRINEY
	setflag FLAG_HIDE_BRINEYS_HOUSE_PEEKO
	releaseall
	end

@ Unused
NewhopeCity_EventScript_ShadyCharacterTookOff::
	msgbox NewhopeCity_Text_ShadyCharacterTookOffTowardsTunnel, MSGBOX_DEFAULT
	return

@ Unused
NewhopeCity_EventScript_YouGotItThankYou::
	msgbox NewhopeCity_Text_YouGotItThankYou, MSGBOX_DEFAULT
	return

@ Unknown, unused employee movements. Based on the differences in movement theyre for approaching an object (probably the player) in different positions
NewhopeCity_EventScript_EmployeeApproachUp::
	applymovement LOCALID_DEVON_EMPLOYEE, NewhopeCity_Movement_EmployeeApproachUp
	waitmovement 0
	return

@ Unused, see above
NewhopeCity_EventScript_EmployeeApproachLeft::
	applymovement LOCALID_DEVON_EMPLOYEE, NewhopeCity_Movement_EmployeeApproachLeft
	waitmovement 0
	return

@ Unused, see above
NewhopeCity_EventScript_EmployeeApproachRight::
	applymovement LOCALID_DEVON_EMPLOYEE, NewhopeCity_Movement_EmployeeApproachRight
	waitmovement 0
	return

@ Unused, see above
NewhopeCity_EventScript_EmployeeApproachDown::
	applymovement LOCALID_DEVON_EMPLOYEE, NewhopeCity_Movement_EmployeeApproachDown
	waitmovement 0
	return

@ Unused, similar movement to the above scripts
NewhopeCity_EventScript_EmployeeApproachPlayerFar::
	applymovement LOCALID_DEVON_EMPLOYEE, NewhopeCity_Movement_EmployeeApproachPlayerFar
	waitmovement 0
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkInPlaceFasterUp
	waitmovement 0
	return

@ Unused
NewhopeCity_Movement_GruntEscapeExtended:
	walk_faster_right
	walk_faster_right
	walk_fast_right
	walk_fast_right
	walk_fast_right
	walk_fast_right
	walk_fast_up
	walk_fast_up
	walk_fast_up
	walk_fast_up
	walk_fast_up
	walk_fast_up
	walk_fast_up
	walk_fast_up
	walk_fast_up
	walk_fast_up
	walk_fast_up
	step_end

NewhopeCity_Movement_GruntEscape:
	walk_faster_right
	walk_faster_right
	walk_fast_right
	walk_fast_right
	walk_fast_right
	walk_fast_right
	walk_fast_right
	walk_fast_up
	walk_fast_up
	walk_fast_up
	walk_fast_up
	walk_fast_up
	walk_fast_up
	walk_fast_up
	walk_fast_up
	walk_fast_up
	step_end

NewhopeCity_Movement_EmployeeChaseGrunt1:
	walk_right
	walk_right
	walk_right
	walk_right
	walk_right
	walk_right
	walk_in_place_faster_up
	step_end

NewhopeCity_Movement_EmployeeChaseGrunt2:
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

@ Functionally unused
NewhopeCity_Movement_EmployeeApproachUp:
	walk_down
	walk_right
	walk_right
	step_end

@ Functionally unused
NewhopeCity_Movement_EmployeeApproachLeft:
	walk_down
	walk_down
	walk_right
	walk_right
	step_end

@ Functionally unused
NewhopeCity_Movement_EmployeeApproachRight:
	walk_down
	walk_down
	walk_right
	walk_right
	step_end

@ Functionally unused
NewhopeCity_Movement_EmployeeApproachDown:
	walk_down
	walk_down
	walk_down
	walk_right
	walk_right
	step_end

@ Functionally unused
NewhopeCity_Movement_EmployeeApproachPlayerFar:
	walk_down
	walk_down
	walk_down
	walk_right
	walk_right
	walk_right
	walk_in_place_faster_down
	step_end

NewhopeCity_EventScript_DevonEmployee1::
	lock
	faceplayer
	goto_if_set FLAG_RECOVERED_DEVON_GOODS, NewhopeCity_EventScript_ReturnGoodsSpokeToEmployee
	msgbox NewhopeCity_Text_ShadyCharacterTookOffTowardsTunnel, MSGBOX_DEFAULT
	release
	end

NewhopeCity_EventScript_ReturnGoodsSpokeToEmployee::
	waitse
	setvar VAR_TEMP_1, 4
	goto NewhopeCity_EventScript_ReturnGoods
	end

NewhopeCity_EventScript_HelpGetGoodsTrigger0::
	lockall
	setvar VAR_TEMP_1, 0
	goto NewhopeCity_EventScript_EmployeeAskToGetGoods
	end

NewhopeCity_EventScript_HelpGetGoodsTrigger1::
	lockall
	setvar VAR_TEMP_1, 1
	goto NewhopeCity_EventScript_EmployeeAskToGetGoods
	end

NewhopeCity_EventScript_HelpGetGoodsTrigger2::
	lockall
	setvar VAR_TEMP_1, 2
	goto NewhopeCity_EventScript_EmployeeAskToGetGoods
	end

NewhopeCity_EventScript_HelpGetGoodsTrigger3::
	lockall
	setvar VAR_TEMP_1, 3
	goto NewhopeCity_EventScript_EmployeeAskToGetGoods
	end

NewhopeCity_EventScript_EmployeeAskToGetGoods::
	call_if_eq VAR_TEMP_1, 0, NewhopeCity_EventScript_EmployeeFacePlayerUp1
	call_if_eq VAR_TEMP_1, 1, NewhopeCity_EventScript_EmployeeFacePlayerLeft1
	call_if_eq VAR_TEMP_1, 2, NewhopeCity_EventScript_EmployeeFacePlayerDown1
	call_if_eq VAR_TEMP_1, 3, NewhopeCity_EventScript_EmployeeApproachPlayerDown1
	setflag FLAG_INTERACTED_WITH_DEVON_EMPLOYEE_GOODS_STOLEN
	setvar VAR_NEWHOPE_CITY_STATE, 3
	copyobjectxytoperm LOCALID_DEVON_EMPLOYEE
	msgbox NewhopeCity_Text_HelpMeIWasRobbed, MSGBOX_DEFAULT
	releaseall
	end

@ The below movement scripts are either partially or fully duplicated by the movement scripts when the player returns the goods
NewhopeCity_EventScript_EmployeeFacePlayerUp1::
	applymovement LOCALID_DEVON_EMPLOYEE, Common_Movement_WalkInPlaceFasterUp
	waitmovement 0
	playse SE_PIN
	applymovement LOCALID_DEVON_EMPLOYEE, Common_Movement_ExclamationMark
	waitmovement 0
	applymovement LOCALID_DEVON_EMPLOYEE, Common_Movement_Delay48
	waitmovement 0
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkInPlaceFasterDown
	waitmovement 0
	return

NewhopeCity_EventScript_EmployeeFacePlayerLeft1::
	applymovement LOCALID_DEVON_EMPLOYEE, Common_Movement_WalkInPlaceFasterLeft
	waitmovement 0
	playse SE_PIN
	applymovement LOCALID_DEVON_EMPLOYEE, Common_Movement_ExclamationMark
	waitmovement 0
	applymovement LOCALID_DEVON_EMPLOYEE, Common_Movement_Delay48
	waitmovement 0
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_FaceRight
	waitmovement 0
	return

NewhopeCity_EventScript_EmployeeFacePlayerDown1::
	applymovement LOCALID_DEVON_EMPLOYEE, Common_Movement_WalkInPlaceFasterDown
	waitmovement 0
	playse SE_PIN
	applymovement LOCALID_DEVON_EMPLOYEE, Common_Movement_ExclamationMark
	waitmovement 0
	applymovement LOCALID_DEVON_EMPLOYEE, Common_Movement_Delay48
	waitmovement 0
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkInPlaceFasterUp
	waitmovement 0
	return

NewhopeCity_EventScript_EmployeeApproachPlayerDown1::
	applymovement LOCALID_DEVON_EMPLOYEE, Common_Movement_WalkInPlaceFasterDown
	waitmovement 0
	playse SE_PIN
	applymovement LOCALID_DEVON_EMPLOYEE, Common_Movement_ExclamationMark
	waitmovement 0
	applymovement LOCALID_DEVON_EMPLOYEE, Common_Movement_Delay48
	waitmovement 0
	applymovement LOCALID_DEVON_EMPLOYEE, NewhopeCity_Movement_EmployeeApproachPlayerDown
	waitmovement 0
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkInPlaceFasterUp
	waitmovement 0
	return

NewhopeCity_Movement_EmployeeApproachPlayerDown:
	walk_down
	step_end

NewhopeCity_EventScript_ReturnGoodsTrigger0::
	lockall
	setvar VAR_TEMP_1, 0
	goto NewhopeCity_EventScript_ReturnGoods
	end

NewhopeCity_EventScript_ReturnGoodsTrigger1::
	lockall
	setvar VAR_TEMP_1, 1
	goto NewhopeCity_EventScript_ReturnGoods
	end

NewhopeCity_EventScript_ReturnGoodsTrigger2::
	lockall
	setvar VAR_TEMP_1, 2
	goto NewhopeCity_EventScript_ReturnGoods
	end

NewhopeCity_EventScript_ReturnGoodsTrigger3::
	lockall
	setvar VAR_TEMP_1, 3
	goto NewhopeCity_EventScript_ReturnGoods
	end

NewhopeCity_EventScript_ReturnGoods::
	call_if_eq VAR_TEMP_1, 0, NewhopeCity_EventScript_EmployeeFacePlayerUp2
	call_if_eq VAR_TEMP_1, 1, NewhopeCity_EventScript_EmployeeFacePlayerLeft2
	call_if_eq VAR_TEMP_1, 2, NewhopeCity_EventScript_EmployeeFacePlayerDown2
	call_if_eq VAR_TEMP_1, 3, NewhopeCity_EventScript_EmployeeApproachPlayerDown2
	call_if_eq VAR_TEMP_1, 4, NewhopeCity_EventScript_EmployeeFacePlayerRight
	msgbox NewhopeCity_Text_YouGotItThankYou, MSGBOX_DEFAULT
	giveitem ITEM_GREAT_BALL
	call_if_eq VAR_RESULT, FALSE, NewhopeCity_EventScript_BagFull
	msgbox NewhopeCity_Text_PleaseComeWithMe, MSGBOX_DEFAULT
	closemessage
	setflag FLAG_RETURNED_DEVON_GOODS
	setflag FLAG_HIDE_NEWHOPE_CITY_DEVON_EMPLOYEE_1
	setvar VAR_NEWHOPE_CITY_STATE, 5
	delay 30
	warp MAP_NEWHOPE_CITY_DEVON_CORP_3F, 2, 2
	waitstate
	releaseall
	end

NewhopeCity_EventScript_BagFull::
	msgbox NewhopeCity_Text_YoureLoadedWithItems, MSGBOX_DEFAULT
	return

NewhopeCity_EventScript_EmployeeFacePlayerUp2::
	applymovement LOCALID_DEVON_EMPLOYEE, Common_Movement_WalkInPlaceFasterUp
	waitmovement 0
	playse SE_PIN
	applymovement LOCALID_DEVON_EMPLOYEE, Common_Movement_ExclamationMark
	waitmovement 0
	applymovement LOCALID_DEVON_EMPLOYEE, Common_Movement_Delay48
	waitmovement 0
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkInPlaceFasterDown
	waitmovement 0
	return

NewhopeCity_EventScript_EmployeeFacePlayerLeft2::
	applymovement LOCALID_DEVON_EMPLOYEE, Common_Movement_WalkInPlaceFasterRight
	waitmovement 0
	playse SE_PIN
	applymovement LOCALID_DEVON_EMPLOYEE, Common_Movement_ExclamationMark
	waitmovement 0
	applymovement LOCALID_DEVON_EMPLOYEE, Common_Movement_Delay48
	waitmovement 0
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_FaceLeft
	waitmovement 0
	return

NewhopeCity_EventScript_EmployeeFacePlayerDown2::
	applymovement LOCALID_DEVON_EMPLOYEE, Common_Movement_WalkInPlaceFasterDown
	waitmovement 0
	playse SE_PIN
	applymovement LOCALID_DEVON_EMPLOYEE, Common_Movement_ExclamationMark
	waitmovement 0
	applymovement LOCALID_DEVON_EMPLOYEE, Common_Movement_Delay48
	waitmovement 0
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkInPlaceFasterUp
	waitmovement 0
	return

NewhopeCity_EventScript_EmployeeApproachPlayerDown2::
	applymovement LOCALID_DEVON_EMPLOYEE, Common_Movement_WalkInPlaceFasterDown
	waitmovement 0
	playse SE_PIN
	applymovement LOCALID_DEVON_EMPLOYEE, Common_Movement_ExclamationMark
	waitmovement 0
	applymovement LOCALID_DEVON_EMPLOYEE, Common_Movement_Delay48
	waitmovement 0
	applymovement LOCALID_DEVON_EMPLOYEE, NewhopeCity_Movement_EmployeeApproachPlayerDown
	waitmovement 0
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkInPlaceFasterUp
	waitmovement 0
	return

NewhopeCity_EventScript_EmployeeFacePlayerRight::
	applymovement LOCALID_DEVON_EMPLOYEE, Common_Movement_WalkInPlaceFasterLeft
	waitmovement 0
	playse SE_PIN
	applymovement LOCALID_DEVON_EMPLOYEE, Common_Movement_ExclamationMark
	waitmovement 0
	applymovement LOCALID_DEVON_EMPLOYEE, Common_Movement_Delay48
	waitmovement 0
	return

NewhopeCity_EventScript_Rival::
	lockall
	call_if_unset FLAG_MET_RIVAL_NEWHOPE, NewhopeCity_EventScript_PlayRivalMusic
	applymovement LOCALID_RIVAL, Common_Movement_FacePlayer
	waitmovement 0
	goto NewhopeCity_EventScript_RivalEncounter

NewhopeCity_EventScript_PlayRivalMusic::
	checkplayergender
	goto_if_eq VAR_RESULT, MALE, NewhopeCity_EventScript_PlayMayMusic
	goto_if_eq VAR_RESULT, FEMALE, NewhopeCity_EventScript_PlayBrendanMusic
	return

NewhopeCity_EventScript_PlayMayMusic::
	playbgm MUS_ENCOUNTER_MAY, TRUE
	return

NewhopeCity_EventScript_PlayBrendanMusic::
	playbgm MUS_ENCOUNTER_BRENDAN, TRUE
	return

NewhopeCity_EventScript_RivalTrigger0::
	lockall
	call NewhopeCity_EventScript_PlayRivalMusic
	applymovement LOCALID_RIVAL, Common_Movement_WalkInPlaceFasterDown
	waitmovement 0
	playse SE_PIN
	applymovement LOCALID_RIVAL, Common_Movement_ExclamationMark
	waitmovement 0
	applymovement LOCALID_RIVAL, Common_Movement_Delay48
	waitmovement 0
	applymovement LOCALID_RIVAL, NewhopeCity_Movement_RivalApproachPlayer0
	waitmovement 0
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkInPlaceFasterUp
	waitmovement 0
	goto NewhopeCity_EventScript_RivalEncounter

NewhopeCity_EventScript_RivalTrigger1::
	lockall
	call NewhopeCity_EventScript_PlayRivalMusic
	applymovement LOCALID_RIVAL, Common_Movement_WalkInPlaceFasterDown
	waitmovement 0
	playse SE_PIN
	applymovement LOCALID_RIVAL, Common_Movement_ExclamationMark
	waitmovement 0
	applymovement LOCALID_RIVAL, Common_Movement_Delay48
	waitmovement 0
	applymovement LOCALID_RIVAL, NewhopeCity_Movement_RivalApproachPlayer1
	waitmovement 0
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkInPlaceFasterUp
	waitmovement 0
	goto NewhopeCity_EventScript_RivalEncounter

NewhopeCity_EventScript_RivalTrigger2::
	lockall
	call NewhopeCity_EventScript_PlayRivalMusic
	applymovement LOCALID_RIVAL, Common_Movement_WalkInPlaceFasterDown
	waitmovement 0
	playse SE_PIN
	applymovement LOCALID_RIVAL, Common_Movement_ExclamationMark
	waitmovement 0
	applymovement LOCALID_RIVAL, Common_Movement_Delay48
	waitmovement 0
	applymovement LOCALID_RIVAL, NewhopeCity_Movement_RivalApproachPlayer2
	waitmovement 0
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkInPlaceFasterUp
	waitmovement 0
	goto NewhopeCity_EventScript_RivalEncounter

NewhopeCity_EventScript_RivalTrigger3::
	lockall
	call NewhopeCity_EventScript_PlayRivalMusic
	applymovement LOCALID_RIVAL, Common_Movement_WalkInPlaceFasterDown
	waitmovement 0
	playse SE_PIN
	applymovement LOCALID_RIVAL, Common_Movement_ExclamationMark
	waitmovement 0
	applymovement LOCALID_RIVAL, Common_Movement_Delay48
	waitmovement 0
	applymovement LOCALID_RIVAL, NewhopeCity_Movement_RivalApproachPlayer3
	waitmovement 0
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkInPlaceFasterUp
	waitmovement 0
	goto NewhopeCity_EventScript_RivalEncounter

NewhopeCity_EventScript_RivalTrigger4::
	lockall
	call NewhopeCity_EventScript_PlayRivalMusic
	applymovement LOCALID_RIVAL, Common_Movement_WalkInPlaceFasterDown
	waitmovement 0
	playse SE_PIN
	applymovement LOCALID_RIVAL, Common_Movement_ExclamationMark
	waitmovement 0
	applymovement LOCALID_RIVAL, Common_Movement_Delay48
	waitmovement 0
	applymovement LOCALID_RIVAL, NewhopeCity_Movement_RivalApproachPlayer4
	waitmovement 0
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkInPlaceFasterUp
	waitmovement 0
	goto NewhopeCity_EventScript_RivalEncounter

NewhopeCity_EventScript_RivalTrigger5::
	lockall
	call NewhopeCity_EventScript_PlayRivalMusic
	applymovement LOCALID_RIVAL, Common_Movement_WalkInPlaceFasterDown
	waitmovement 0
	playse SE_PIN
	applymovement LOCALID_RIVAL, Common_Movement_ExclamationMark
	waitmovement 0
	applymovement LOCALID_RIVAL, Common_Movement_Delay48
	waitmovement 0
	applymovement LOCALID_RIVAL, NewhopeCity_Movement_RivalApproachPlayer5
	waitmovement 0
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkInPlaceFasterUp
	waitmovement 0
	goto NewhopeCity_EventScript_RivalEncounter

NewhopeCity_EventScript_RivalTrigger6::
	lockall
	call NewhopeCity_EventScript_PlayRivalMusic
	applymovement LOCALID_RIVAL, Common_Movement_WalkInPlaceFasterDown
	waitmovement 0
	playse SE_PIN
	applymovement LOCALID_RIVAL, Common_Movement_ExclamationMark
	waitmovement 0
	applymovement LOCALID_RIVAL, Common_Movement_Delay48
	waitmovement 0
	applymovement LOCALID_RIVAL, NewhopeCity_Movement_RivalApproachPlayer6
	waitmovement 0
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkInPlaceFasterUp
	waitmovement 0
	goto NewhopeCity_EventScript_RivalEncounter

NewhopeCity_EventScript_RivalTrigger7::
	lockall
	call NewhopeCity_EventScript_PlayRivalMusic
	applymovement LOCALID_RIVAL, Common_Movement_WalkInPlaceFasterDown
	waitmovement 0
	playse SE_PIN
	applymovement LOCALID_RIVAL, Common_Movement_ExclamationMark
	waitmovement 0
	applymovement LOCALID_RIVAL, Common_Movement_Delay48
	waitmovement 0
	applymovement LOCALID_RIVAL, NewhopeCity_Movement_RivalApproachPlayer7
	waitmovement 0
	applymovement OBJ_EVENT_ID_PLAYER, Common_Movement_WalkInPlaceFasterUp
	waitmovement 0
	goto NewhopeCity_EventScript_RivalEncounter

NewhopeCity_EventScript_RivalEncounter::
	checkplayergender
	goto_if_eq VAR_RESULT, MALE, NewhopeCity_EventScript_MayEncounter
	goto_if_eq VAR_RESULT, FEMALE, NewhopeCity_EventScript_BrendanEncounter
	end

NewhopeCity_EventScript_MayEncounter::
	goto_if_set FLAG_DEFEATED_RIVAL_NEWHOPE, NewhopeCity_EventScript_MayBrineyHint
	goto_if_set FLAG_MET_RIVAL_NEWHOPE, NewhopeCity_EventScript_MayAskToBattle
	setflag FLAG_MET_RIVAL_NEWHOPE
	msgbox NewhopeCity_Text_MayHiLetsRegister, MSGBOX_DEFAULT
	closemessage
	delay 30
	playfanfare MUS_REGISTER_MATCH_CALL
	msgbox NewhopeCity_Text_RegisteredMay, MSGBOX_DEFAULT
	waitfanfare
	closemessage
	delay 30
	setflag FLAG_ENABLE_RIVAL_MATCH_CALL
	setvar VAR_NEWHOPE_CITY_STATE, 8
	setvar VAR_ROUTE104_STATE, 2
	setvar VAR_0x8008, 0
	msgbox NewhopeCity_Text_MayPassedBrineyWantToBattle, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, NewhopeCity_EventScript_BattleMay
	msgbox NewhopeCity_Text_MayOhHaventRaisedPokemonEnough, MSGBOX_DEFAULT
	call NewhopeCity_EventScript_RestoreBgm
	releaseall
	end

NewhopeCity_EventScript_MayAskToBattle::
	setvar VAR_0x8008, 1
	msgbox NewhopeCity_Text_MayWantToBattle, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, NewhopeCity_EventScript_BattleMay
	msgbox NewhopeCity_Text_MayOhHaventRaisedPokemonEnough, MSGBOX_DEFAULT
	releaseall
	end

NewhopeCity_EventScript_BattleMay::
	msgbox NewhopeCity_Text_MayImNotGoingToLose, MSGBOX_DEFAULT
	switch VAR_STARTER_MON
	case 0, NewhopeCity_EventScript_BattleMayTreecko
	case 1, NewhopeCity_EventScript_BattleMayTorchic
	case 2, NewhopeCity_EventScript_BattleMayMudkip
	end

NewhopeCity_EventScript_MayBrineyHint::
	msgbox NewhopeCity_Text_MayMrBrineyHint, MSGBOX_DEFAULT
	call_if_eq VAR_0x8008, 0, NewhopeCity_EventScript_RestoreBgm
	releaseall
	end

NewhopeCity_EventScript_RestoreBgm::
	savebgm MUS_DUMMY
	fadedefaultbgm
	return

NewhopeCity_EventScript_BattleMayTreecko::
	trainerbattle_no_intro TRAINER_MAY_NEWHOPE_TREECKO, NewhopeCity_Text_MayDefeat
	setflag FLAG_DEFEATED_RIVAL_NEWHOPE
	goto NewhopeCity_EventScript_MayBrineyHint
	end

NewhopeCity_EventScript_BattleMayTorchic::
	trainerbattle_no_intro TRAINER_MAY_NEWHOPE_TORCHIC, NewhopeCity_Text_MayDefeat
	setflag FLAG_DEFEATED_RIVAL_NEWHOPE
	goto NewhopeCity_EventScript_MayBrineyHint
	end

NewhopeCity_EventScript_BattleMayMudkip::
	trainerbattle_no_intro TRAINER_MAY_NEWHOPE_MUDKIP, NewhopeCity_Text_MayDefeat
	setflag FLAG_DEFEATED_RIVAL_NEWHOPE
	goto NewhopeCity_EventScript_MayBrineyHint
	end

NewhopeCity_EventScript_BrendanEncounter::
	goto_if_set FLAG_DEFEATED_RIVAL_NEWHOPE, NewhopeCity_EventScript_BrendanBrineyHint
	goto_if_set FLAG_MET_RIVAL_NEWHOPE, NewhopeCity_EventScript_BrendanAskToBattle
	setflag FLAG_MET_RIVAL_NEWHOPE
	msgbox NewhopeCity_Text_BrendanHiLetsRegister, MSGBOX_DEFAULT
	closemessage
	delay 30
	playfanfare MUS_REGISTER_MATCH_CALL
	msgbox NewhopeCity_Text_RegisteredBrendan, MSGBOX_DEFAULT
	waitfanfare
	closemessage
	delay 30
	setflag FLAG_ENABLE_RIVAL_MATCH_CALL
	setvar VAR_NEWHOPE_CITY_STATE, 8
	setvar VAR_ROUTE104_STATE, 2
	msgbox NewhopeCity_Text_BrendanPassedBrineyWantToBattle, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, NewhopeCity_EventScript_BattleBrendan
	msgbox NewhopeCity_Text_BrendanNoConfidenceInPokemon, MSGBOX_DEFAULT
	call NewhopeCity_EventScript_RestoreBgm
	releaseall
	end

NewhopeCity_EventScript_BrendanAskToBattle::
	msgbox NewhopeCity_Text_BrendanWantToBattle, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, NewhopeCity_EventScript_BattleBrendan
	msgbox NewhopeCity_Text_BrendanNoConfidenceInPokemon, MSGBOX_DEFAULT
	releaseall
	end

NewhopeCity_EventScript_BattleBrendan::
	msgbox NewhopeCity_Text_BrendanIWontGoEasy, MSGBOX_DEFAULT
	switch VAR_STARTER_MON
	case 0, NewhopeCity_EventScript_BattleBrendanTreecko
	case 1, NewhopeCity_EventScript_BattleBrendanTorchic
	case 2, NewhopeCity_EventScript_BattleBrendanMudkip
	end

NewhopeCity_EventScript_BrendanBrineyHint::
	msgbox NewhopeCity_Text_BrendanMrBrineyHint, MSGBOX_DEFAULT
	call_if_eq VAR_0x8008, 0, NewhopeCity_EventScript_RestoreBgm
	releaseall
	end

NewhopeCity_EventScript_BattleBrendanTreecko::
	trainerbattle_no_intro TRAINER_BRENDAN_NEWHOPE_TREECKO, NewhopeCity_Text_BrendanDefeat
	setflag FLAG_DEFEATED_RIVAL_NEWHOPE
	goto NewhopeCity_EventScript_BrendanBrineyHint
	end

NewhopeCity_EventScript_BattleBrendanTorchic::
	trainerbattle_no_intro TRAINER_BRENDAN_NEWHOPE_TORCHIC, NewhopeCity_Text_BrendanDefeat
	setflag FLAG_DEFEATED_RIVAL_NEWHOPE
	goto NewhopeCity_EventScript_BrendanBrineyHint
	end

NewhopeCity_EventScript_BattleBrendanMudkip::
	trainerbattle_no_intro TRAINER_BRENDAN_NEWHOPE_MUDKIP, NewhopeCity_Text_BrendanDefeat
	setflag FLAG_DEFEATED_RIVAL_NEWHOPE
	goto NewhopeCity_EventScript_BrendanBrineyHint
	end

NewhopeCity_Movement_RivalApproachPlayer0:
	walk_down
	walk_left
	walk_left
	walk_left
	walk_left
	walk_down
	step_end

NewhopeCity_Movement_RivalApproachPlayer1:
	walk_down
	walk_left
	walk_left
	walk_left
	walk_down
	step_end

NewhopeCity_Movement_RivalApproachPlayer2:
	walk_down
	walk_left
	walk_left
	walk_down
	step_end

NewhopeCity_Movement_RivalApproachPlayer3:
	walk_down
	walk_left
	walk_down
	step_end

NewhopeCity_Movement_RivalApproachPlayer4:
	walk_down
	walk_down
	step_end

NewhopeCity_Movement_RivalApproachPlayer5:
	walk_down
	walk_right
	walk_down
	step_end

NewhopeCity_Movement_RivalApproachPlayer6:
	walk_down
	walk_right
	walk_right
	walk_down
	step_end

NewhopeCity_Movement_RivalApproachPlayer7:
	walk_down
	walk_right
	walk_right
	walk_right
	walk_down
	step_end

NewhopeCity_EventScript_Boy1::
	msgbox NewhopeCity_Text_YouCanHave2On2Battle, MSGBOX_NPC
	end

NewhopeCity_Text_WeShortenItToDevon:
	.string "The DEVON CORPORATION…\n"
	.string "We all just shorten it to DEVON.\p"
	.string "That company makes all sorts of\n"
	.string "convenient products.$"

NewhopeCity_Text_SneakyLookingManWentAroundCorner:
	.string "Hm? A sneaky-looking man?\p"
	.string "Come to think of it, yes, a shady-\n"
	.string "looking guy went around the corner.$"

NewhopeCity_Text_HaveYouChallengedGym:
	.string "Have you taken the POKéMON GYM\n"
	.string "challenge?\p"
	.string "When you get that shiny GYM BADGE\n"
	.string "in hand, I guess TRAINERS begin to\l"
	.string "realize what is required of them.$"

NewhopeCity_Text_HeyThatsNewhopesGymBadge:
	.string "Hey, that's NEWHOPE's GYM BADGE!\p"
	.string "Out of all the POKéMON GYM BADGES,\n"
	.string "NEWHOPE's is the coolest, I'd say.$"

NewhopeCity_Text_YoureNewAroundHere:
	.string "Oh? Who might you be?\n"
	.string "You're a new face around these parts.\p"
	.string "Have you just transferred into the\n"
	.string "POKéMON TRAINER'S SCHOOL?$"

NewhopeCity_Text_GymLeaderIsntEasyWithFire:
	.string "I challenged the GYM LEADER, but…\p"
	.string "It's not going to be easy winning with\n"
	.string "my FIRE-type POKéMON…\p"
	.string "FIRE-type POKéMON don't match up\n"
	.string "well against ROCK-type POKéMON…$"

NewhopeCity_Text_MrBrineyWalksInTheTunnel:
	.string "The old sailor MR. BRINEY lives in\n"
	.string "a cottage by the sea.\p"
	.string "He goes for walks in the tunnel every\n"
	.string "so often.$"

NewhopeCity_Text_MrBrineyLovesPeeko:
	.string "The old sailor MR. BRINEY lives in\n"
	.string "a cottage by the sea.\p"
	.string "He said he was going shopping in\n"
	.string "SLATEPORT for his pet, PEEKO.\p"
	.string "That old sea dog, he must really love\n"
	.string "that PEEKO.$"

NewhopeCity_Text_WowYouHavePokemon:
	.string "Wow, you have POKéMON with you, too.\p"
	.string "When I get bigger, I'm going to go\n"
	.string "places with POKéMON, too.$"

NewhopeCity_Text_CatchRarePokemonIfIGoToSchool:
	.string "POKéMON TRAINER'S SCHOOL!\p"
	.string "If I go to this school, will I be able\n"
	.string "to catch rare POKéMON easily?$"

NewhopeCity_Text_PokemonCanChangeLookFromExp:
	.string "If a POKéMON gains experience in\n"
	.string "battles, it can sometimes change in\l"
	.string "the way it looks.$"

NewhopeCity_Text_PokemonChangeShape:
	.string "A POKéMON changes shape?\n"
	.string "If one did that, I would be shocked!$"

NewhopeCity_Text_TradePokemonGrowFast:
	.string "A POKéMON you get in a trade from\n"
	.string "someone grows fast.\p"
	.string "But if you don't have certain GYM\n"
	.string "BADGES, it may not obey you…$"

NewhopeCity_Text_OutOfTheWay:
	.string "Get out!\n"
	.string "Out of the way!$"

NewhopeCity_Text_WaitDontTakeMyGoods:
	.string "Wait! Pleeeaaase!\p"
	.string "Don't take my GOODS!$"

NewhopeCity_Text_HelpMeIWasRobbed:
	.string "Oh, it's you!\p"
	.string "You're that fantastic TRAINER who\n"
	.string "helped me in PETALBURG WOODS!\p"
	.string "Help me! I was robbed by TEAM AQUA!\n"
	.string "I have to get the DEVON GOODS back!\p"
	.string "If I don't…\n"
	.string "I'm going to be in serious trouble.$"

NewhopeCity_Text_ShadyCharacterTookOffTowardsTunnel:
	.string "That shady character, I think he took\n"
	.string "off towards the tunnel over there.$"

NewhopeCity_Text_YouGotItThankYou:
	.string "Oh! How did it go?\n"
	.string "The DEVON GOODS?\p"
	.string "You did!\n"
	.string "You got them back!\p"
	.string "You really are a great TRAINER!\p"
	.string "I know! As my thanks, I'll give you\n"
	.string "another GREAT BALL!$"

NewhopeCity_Text_YoureLoadedWithItems:
	.string "You're loaded with items.\n"
	.string "I can't give you this GREAT BALL.$"

NewhopeCity_Text_PleaseComeWithMe:
	.string "Excuse me, please!\n"
	.string "Please come with me!$"

NewhopeCity_Text_MayHiLetsRegister:
	.string "MAY: Oh, hi, {PLAYER}{KUN}!\p"
	.string "You had a MATCH CALL feature put\n"
	.string "on your POKéNAV!\p"
	.string "Let's register each other so we can\n"
	.string "contact one another anytime!\p"
	.string "… … … … … …$"

NewhopeCity_Text_RegisteredMay:
	.string "Registered MAY\n"
	.string "in the POKéNAV.$"

NewhopeCity_Text_MayPassedBrineyWantToBattle:
	.string "MAY: Oh, by the way, I passed\n"
	.string "MR. BRINEY in PETALBURG WOODS.\p"
	.string "I guess he's on his way home to his\n"
	.string "cottage by the sea.\p"
	.string "How's your POKéDEX coming along,\n"
	.string "{PLAYER}{KUN}? Mine's looking pretty decent!\p"
	.string "So…\n"
	.string "How about a little battle?$"

NewhopeCity_Text_MayOhHaventRaisedPokemonEnough:
	.string "MAY: Oh, what's the matter?\p"
	.string "Haven't you caught or raised your\n"
	.string "POKéMON very much?\p"
	.string "That's not very good for a TRAINER!$"

NewhopeCity_Text_MayWantToBattle:
	.string "MAY: So, what do you think?\n"
	.string "How about a little battle here?$"

NewhopeCity_Text_MayImNotGoingToLose:
	.string "MAY: You just became a TRAINER,\n"
	.string "{PLAYER}{KUN}. I'm not going to lose!$"

NewhopeCity_Text_MayDefeat:
	.string "Yikes!\n"
	.string "You're better than I expected!$"

NewhopeCity_Text_MayMrBrineyHint:
	.string "MAY: Oh, by the way, MR. BRINEY, who\n"
	.string "I just passed…\p"
	.string "{PLAYER}{KUN}, you just moved here so you\n"
	.string "might not know this, but MR. BRINEY\l"
	.string "was once a revered seafarer.$"

NewhopeCity_Text_BrendanHiLetsRegister:
	.string "BRENDAN: Oh, hey, {PLAYER}!\p"
	.string "You had a MATCH CALL feature put\n"
	.string "on your POKéNAV! Cool!\p"
	.string "Let's register each other so we can\n"
	.string "get in touch anytime!\p"
	.string "… … … … … …$"

NewhopeCity_Text_RegisteredBrendan:
	.string "Registered BRENDAN\n"
	.string "in the POKéNAV.$"

NewhopeCity_Text_BrendanPassedBrineyWantToBattle:
	.string "BRENDAN: By the way, {PLAYER}, I walked\n"
	.string "by MR. BRINEY in PETALBURG WOODS.\p"
	.string "I bet he was on his way home to his\n"
	.string "cottage by the sea.\p"
	.string "{PLAYER}, how's your POKéDEX?\n"
	.string "Have you filled in any pages yet?\p"
	.string "Mine rules.\p"
	.string "Want to have a battle to test how\n"
	.string "far you've progressed?$"

NewhopeCity_Text_BrendanNoConfidenceInPokemon:
	.string "BRENDAN: What's the matter? Don't have\n"
	.string "any confidence in your POKéMON?$"

NewhopeCity_Text_BrendanWantToBattle:
	.string "BRENDAN: What's up?\n"
	.string "Want to have a battle with me?$"

NewhopeCity_Text_BrendanIWontGoEasy:
	.string "BRENDAN: I know you just became\n"
	.string "a TRAINER, but I won't go easy!$"

NewhopeCity_Text_BrendanDefeat:
	.string "Hmm…\n"
	.string "You're pretty good.$"

NewhopeCity_Text_BrendanMrBrineyHint:
	.string "BRENDAN: By the way, you know\n"
	.string "MR. BRINEY? The guy I just passed?\p"
	.string "I bet you didn't know this, since you\n"
	.string "just moved here, {PLAYER}, but\l"
	.string "MR. BRINEY was once a great sailor.$"

NewhopeCity_Text_TunnelNearingCompletion:
	.string "“Timesaving tunnel nearing\n"
	.string "completion!”\p"
	.string "…Is what it says on the sign, but\n"
	.string "there's also a big “X” splashed\l"
	.string "across it in red paint…$"

NewhopeCity_Text_DevonCorpSign:
	.string "DEVON CORPORATION\p"
	.string "“For all your living needs, we make\n"
	.string "it all.”$"

NewhopeCity_Text_GymSign:
	.string "NEWHOPE CITY POKéMON GYM\n"
	.string "LEADER: ROXANNE\p"
	.string "“The ROCK-loving honors student!”$"

NewhopeCity_Text_DevonCorpBranchOfficeSign:
	.string "DEVON CORP. BRANCH OFFICE\p"
	.string "“Access limited to DEVON employees\n"
	.string "and authorized personnel.”$"

NewhopeCity_Text_CitySign:
	.string "NEWHOPE CITY\p"
	.string "“The city probing the integration of\n"
	.string "nature and science.”$"

NewhopeCity_Text_TrainersSchoolSign:
	.string "POKéMON TRAINER'S SCHOOL\p"
	.string "“We'll teach you anything about\n"
	.string "POKéMON!”$"

NewhopeCity_Text_CuttersHouse:
	.string "CUTTER'S HOUSE$"

NewhopeCity_Text_DevelopedNewPokenavFeature:
	.string "I've been developing an added feature\n"
	.string "for the POKéNAV…\p"
	.string "And it turned out great!\p"
	.string "{PLAYER}, may I see that POKéNAV?\n"
	.string "The one our PRESIDENT gave you?$"

NewhopeCity_Text_AddedMatchCallPleaseCallMrStone:
	.string "There you go, {PLAYER}!\p"
	.string "I added a new feature named\n"
	.string "MATCH CALL to your POKéNAV.\p"
	.string "Using the MATCH CALL feature,\n"
	.string "you can chat with people who have\l"
	.string "been registered in your POKéNAV.\p"
	.string "{PLAYER}, our PRESIDENT STONE should\n"
	.string "be registered in your POKéNAV.\p"
	.string "Test it out.\n"
	.string "Please give our PRESIDENT a call.$"

NewhopeCity_Text_PleaseSelectPokenav:
	.string "Please select the POKéNAV.$"

NewhopeCity_Text_IdBetterGetBackToWork:
	.string "Okay, I'd better get back to work.\n"
	.string "Please take care, {PLAYER}!$"

NewhopeCity_Text_YouCanHave2On2Battle:
	.string "Did you know this?\p"
	.string "You can have a 2-on-2 battle even\n"
	.string "if you're not with another TRAINER.\p"
	.string "If you catch the eyes of two TRAINERS\n"
	.string "when you have two or more POKéMON,\l"
	.string "they'll both challenge you.\p"
	.string "Don't you think it'd be cool if you\n"
	.string "could beat two TRAINERS by yourself?$"
